import Head from "next/head"
import { ConnectButton } from "@rainbow-me/rainbowkit"
import { useAccount } from "wagmi"
import { useIsMounted } from "@/hooks/useIsMounted"

export default function Home() {
	const { mounted } = useIsMounted()
	const { address } = useAccount()

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<>
				<ConnectButton />
				{mounted ? address && <p>Your address is: {address}</p> : null}
			</>
		</>
	)
}
